version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Python
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/async_bot" # Location of requirements.txt
    schedule:
      interval: "daily"

  # Python
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/async_parser" # Location of requirements.txt
    schedule:
      interval: "daily"